exercise2/src/SDFG.Konquest.Dashboard/Models/GuildViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SDFG.Konquest.Dashboard.Models
{
    public class GuildViewModel
    {
        public string Id { get; set; }

        public IEnumerable<Quest> Quests { get; set; }
    }
}

exercise2/src/SDFG.Konquest.Dashboard/Models/NavigationItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SDFG.Konquest.Dashboard.Models
{
    public class NavigationItem
    {
        private readonly string _activeUrl;

        public NavigationItem(string activeUrl)
        {
            _activeUrl = activeUrl;
        }

        public bool IsActive { get {  return _activeUrl == Url; } }

        public string Name { get; set; }

        public string Url { get; set; }

        public string Icon { get; set; }
    }
}

exercise2/src/SDFG.Konquest.Dashboard/Models/Quest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SDFG.Konquest.Dashboard.Models
{
    public class Quest
    {
        public string Title { get; set; }

        public string Content { get; set; }
    }
}

exercise2/src/SDFG.Konquest.Dashboard/Controllers/GuildsController.cs
using Microsoft.AspNet.Mvc;
using SDFG.Konquest.Dashboard.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SDFG.Konquest.Dashboard.Controllers
{
    public class GuildsController : Controller
    {
        public IActionResult Index(string id)
        {
            return View(new GuildViewModel
            {
                Id = id,
                Quests = GetQuests()
            });
        }

        private IEnumerable<Quest> GetQuests()
        {
            var quests = new[]
            {
                new Quest
                {
                    Title = "Presentation noob",
                    Content = "Do one SDFG or AppBite"
                },
                new Quest
                {
                    Title = "Presentation novice",
                    Content = "Do two SDFG's or AppBites"
                },
                new Quest
                {
                    Title = "Presentation master",
                    Content = "Do five SDFG's or AppBites"
                },
                new Quest
                {
                    Title = "Get certified",
                    Content = "Get one certificate"
                },
                new Quest
                {
                    Title = "Certified developer",
                    Content = "Get your MCSD"
                }

            };

            return quests;
        }
    }
}

exercise2/src/SDFG.Konquest.Dashboard/Controllers/HomeController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SDFG.Konquest.Dashboard.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

exercise2/src/SDFG.Konquest.Dashboard/Views/Guilds/Index.cshtml
@model SDFG.Konquest.Dashboard.Models.GuildViewModel

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var imgSrc = Url.Content($"/images/emblems/{Model.Id}_800.png");
}

<h1 class="mdl-typography--text-center"><img src="@imgSrc" alt="@Model.Id" class="quest-title-img" /></h1>

<div class="mdl-grid quest-cards">
    <div class="mdl-cell mdl-cell--12-col mdl-color-text--blue-500"><h2>Quests</h2></div>
    @foreach (var quest in Model.Quests)
    {
        <div class="mdl-cell mdl-cell--12-col">
            <div class="demo-card-event mdl-card mdl-shadow--2dp mdl-color--blue-500">
                <div class="mdl-card__title mdl-card--expand mdl-color-text--white">
                    <h4>
                        @quest.Title
                    </h4>
                </div>
                <div class="mdl-card__supporting-text mdl-color-text--white">
                    @quest.Content
                </div>
                <div class="mdl-card__actions mdl-card--border mdl-color--blue-700">
                    <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
                        View Quest
                    </a>
                </div>
            </div>
        </div>
    }
</div>

exercise2/src/SDFG.Konquest.Dashboard/Views/Home/Index.cshtml
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet">
        <div class="card-image card-image-web mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand"></div>
            <div class="mdl-card__actions">
                <a href="@Url.Action("Index", "Guilds", new { id = "web" })" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    Web Guild
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet">
        <div class="card-image card-image-sitecore mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand"></div>
            <div class="mdl-card__actions">
                <a href="@Url.Action("Index", "Guilds", new { id = "sitecore" })" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    Sitecore Guild
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet">
        <div class="card-image card-image-mobility mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand"></div>
            <div class="mdl-card__actions">
                <a href="@Url.Action("Index", "Guilds", new { id = "mobility" })" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    Mobility Guild
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet">
        <div class="card-image card-image-api mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand"></div>
            <div class="mdl-card__actions">
                <a href="@Url.Action("Index", "Guilds", new { id = "api" })" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    API Guild
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet">
        <div class="card-image card-image-iot mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand"></div>
            <div class="mdl-card__actions">
                <a href="@Url.Action("Index", "Guilds", new { id = "iot" })" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    IOT Guild
                </a>
            </div>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet">
        <div class="card-image card-image-sharepoint mdl-card mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand"></div>
            <div class="mdl-card__actions">
                <a href="@Url.Action("Index", "Guilds", new { id = "sharepoint" })" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                    Sharepoint Guild
                </a>
            </div>
        </div>
    </div>
</div>

exercise2/src/SDFG.Konquest.Dashboard/Views/Shared/Components/Drawer/Default.cshtml
@model IEnumerable<SDFG.Konquest.Dashboard.Models.NavigationItem>

<div id="drawer" class="mdl-layout__drawer">
    <div class="mdl-layout-title mdl-color--blue-500 mdl-color-text--white">
        <span class="mdl-layout-title__logo">Konquest</span>
    </div>
    <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="~/">Home</a>
        <div class="konquest-drawer-separator"></div>
        <p class="mdl-navigation__link konquest-navigation__link--header mdl-color-text--blue-500">Guilds</p>
        @foreach (var item in Model)
        {
            var activeClass = item.IsActive ? "mdl-navigation__link--current" : null;

            <a class="mdl-navigation__link @activeClass" href="@item.Url">
                @if (item.Icon != null)
                {
                    <i class="mdl-color-text--blue-grey-400 konquest-icon konquest-icon--@item.Icon" role="presentation"></i>
                }
                @item.Name
            </a>

        }
    </nav>
</div>

exercise2/src/SDFG.Konquest.Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
    <title>Konquest - @ViewBag.Title</title>

    <!-- CSS  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="~/css/material.min.css" />
    <link href="~/css/main.css" type="text/css" rel="stylesheet">
</head>
<body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
        <header class="mdl-layout__header mdl-color--blue-700">
            <div class="mdl-layout--large-screen-only mdl-layout__header-row">
            </div>
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <h3>Avanade Konquest</h3>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                </nav>
            </div>
        </header>
        <!-- ############################# -->
        <!-- drawer navigation             -->
        <!-- add the DrawerComponent Here: -->
        
        <!-- ############################# -->

        <main class="mdl-layout__content mdl-color--grey-100">
            <div class="page-content">
                @RenderBody()
            </div>
        </main>
    </div>
    
    <script type="text/javascript" src="~/js/material.min.js"></script>
</body>
</html>